# Generated by Django 4.0.6 on 2022-07-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[(0, 'PENDING'), (1, 'ON_GOING'), (2, 'DONE')], max_length=1)),
                ('info', models.CharField(max_length=250)),
            ],
        ),
    ]
