# Generated by Django 4.0.6 on 2022-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='steps',
            field=models.TextField(default='[{"name": "All relevant Github pull requests have been merged", "state": "off"}, {"name": "CHANGELOG.md files have been updated", "state": "off"}, {"name": "All tests are passing", "state": "off"}, {"name": "Releases in Github created", "state": "off"}, {"name": "Deployed in demo", "state": "off"}, {"name": "Test Thoroughly in demo", "state": "off"}, {"name": "Deployed in production", "state": "off"}]'),
        ),
        migrations.AlterField(
            model_name='release',
            name='info',
            field=models.TextField(),
        ),
    ]
