# Generated by Django 4.0.6 on 2022-07-17 11:36

from django.db import migrations, models
import releases.models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0004_alter_release_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='steps',
            field=models.JSONField(default=releases.models.Release.init_step),
        ),
    ]
