# Generated by Django 4.0.6 on 2022-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0005_alter_release_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
