# Generated by Django 4.0.6 on 2022-07-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0006_alter_release_info_alter_release_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(default='PLANNED', max_length=10),
        ),
    ]
